export const GET_STATE_DATA_LIST = "GET_STATE_DATA_LIST"; 
export const GET_STATE_DATA_LIST_SUCCESS = "GET_STATE_DATA_LIST_SUCCESS"; 
export const GET_STATE_DATA_LIST_ERROR = "GET_STATE_DATA_LIST_ERROR";

export const GET_DISTRICT_DATA_LIST =  "GET_DISTRICT_DATA_LIST"; 
export const GET_DISTRICT_DATA_LIST_SUCCESS =  "GET_DISTRICT_DATA_LIST_SUCCESS"; 
export const GET_DISTRICT_DATA_LIST_ERROR =  "GET_DISTRICT_DATA_LIST_ERROR";

export const GET_TALUKA_DATA_LIST = "GET_TALUKA_DATA_LIST"; 
export const GET_TALUKA_DATA_LIST_SUCCESS = "GET_TALUKA_DATA_LIST_SUCCESS"; 
export const GET_TALUKA_DATA_LIST_ERROR = "GET_TALUKA_DATA_LIST_ERROR";

export const GET_VILLAGE_DATA_LIST = "GET_VILLAGE_DATA_LIST"; 
export const GET_VILLAGE_DATA_LIST_SUCCESS = "GET_VILLAGE_DATA_LIST_SUCCESS"; 
export const GET_VILLAGE_DATA_LIST_ERROR = "GET_VILLAGE_DATA_LIST_ERROR";