export const GET_COMPANY_LIST = "GET_COMPANY_LIST"; 
export const GET_COMPANY_LIST_SUCCESS = "GET_COMPANY_LIST_SUCCESS"; 
export const GET_COMPANY_LIST_ERROR = "GET_COMPANY_LIST_ERROR";

export const ADD_COMPANY_LIST = "ADD_COMPANY_LIST"; 
export const ADD_COMPANY_LIST_SUCCESS = "ADD_COMPANY_LIST_SUCCESS"; 
export const ADD_COMPANY_LIST_ERROR = "ADD_COMPANY_LIST_ERROR";

export const DELETE_COMPANY_LIST = "DELETE_COMPANY_LIST"; 
export const DELETE_COMPANY_LIST_SUCCESS = "DELETE_COMPANY_LIST_SUCCESS"; 
export const DELETE_COMPANY_LIST_ERROR = "DELETE_COMPANY_LIST_ERROR";