/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./node_modules/flowbite-react/lib/**/*.{js,tsx,ts}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    
    colors: {
      primary: {
        50: "#eff6ff",
        100: "#dbeafe",
        200: "#bfdbfe",
        300: "#93c5fd",
        400: "#60a5fa",
        500: "#3b82f6",
        600: "#2563eb",
        700: "#1d4ed8",
        800: "#1e40af",
        900: "#1e3a8a",
      },
      regalblue: '#243c5a',
      Cultured : "#F5F5FA",
      GhostWhite : "#f6f6fb",
      CardBgcolor:"#f6f7f9",
      Gainsboro: "#e8e9f7",
      AntiWhite:"#F0F0F0 ",
      Black: "#000",
      Backgroundcolor:"#111827",
      CardColor:"#1f2937",
      Red:"#e71616",
      danger:"#f87171",
      deletebutton:"#ff6969",
      addbutton:"#5db55d",
      aqua:"#00FFFF",
      LightGreen:"#49e35cb8",
      LightYellow: "#ffefd5",
      yellowgreen:"#9acd32",
      CartBgColor:"#E2DDDD",
      Ivory :"#FEFFED",
      Platinum:"#e3e3e3",
      lightblue:"#e2f3fb",
      inprogress:"#edf8e8",
      done:"#eaebff",
      LightBlack:"#7c7d88",
      SemiTransparent : "#00000080"

    },
    fontFamily: {
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      mono: [
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
    },
    extend: {
      animation: {
        'spin-slow': 'spin 3s linear infinite',
      }
    },
  },
  plugins: [require("flowbite/plugin")],
};
