export const GET_DASHBOARD_DATA_LIST = "GET_DASHBOARD_DATA_LIST"; 
export const GET_DASHBOARD_DATA_LIST_SUCCESS = "GET_DASHBOARD_DATA_LIST_SUCCESS"; 
export const GET_DASHBOARD_DATA_LIST_ERROR = "GET_DASHBOARD_DATA_LIST_ERROR";

export const GET_REPORT_DATA_LIST = "GET_REPORT_DATA_LIST"; 
export const GET_REPORT_DATA_LIST_SUCCESS = "GET_REPORT_DATA_LIST_SUCCESS"; 
export const GET_REPORT_DATA_LIST_ERROR = "GET_REPORT_DATA_LIST_ERROR";

export const REST_REPORT_DATA_LIST = "REST_REPORT_DATA_LIST"; 
export const REST_REPORT_DATA_LIST_SUCCESS = "REST_REPORT_DATA_LIST_SUCCESS"; 
export const REST_REPORT_DATA_LIST_ERROR = "REST_REPORT_DATA_LIST_ERROR";