export const GET_ORDER_LIST = "GET_ORDER_LIST"; 
export const GET_ORDER_LIST_SUCCESS = "GET_ORDER_LIST_SUCCESS"; 
export const GET_ORDER_LIST_ERROR = "GET_ORDER_LIST_ERROR";

export const ADD_ORDER_LIST = "ADD_ORDER_LIST"; 
export const ADD_ORDER_LIST_SUCCESS = "ADD_ORDER_LIST_SUCCESS"; 
export const ADD_ORDER_LIST_ERROR = "ADD_ORDER_LIST_ERROR";

export const GET_ORDER_DETAILS_LIST = "GET_ORDER_DETAILS_LIST"; 
export const GET_ORDER_DETAILS_LIST_SUCCESS = "GET_ORDER_DETAILS_LIST_SUCCESS"; 
export const GET_ORDER_DETAILS_LIST_ERROR = "GET_ORDER_DETAILS_LIST_ERROR";

export const RESET_ORDER_LIST = "RESET_ORDER_LIST"; 
export const RESET_ORDER_LIST_SUCCESS = "RESET_ORDER_LIST_SUCCESS"; 
export const RESET_ORDER_LIST_ERROR = "RESET_ORDER_LIST_ERROR";

export const DELETE_ORDER_LIST = "DELETE_ORDER_LIST"; 
export const DELETE_ORDER_LIST_SUCCESS = "DELETE_ORDER_LIST_SUCCESS"; 
export const DELETE_ORDER_LIST_ERROR = "DELETE_ORDER_LIST_ERROR";

export const GET_UPDATE_ORDER_LIST = "GET_UPDATE_ORDER_LIST"; 
export const GET_UPDATE_ORDER_LIST_SUCCESS = "GET_UPDATE_ORDER_LIST_SUCCESS"; 
export const GET_UPDATE_ORDER_LIST_ERROR = "GET_UPDATE_ORDER_LIST_ERROR";
