export const GET_MODULE_ACCESS_LIST = "GET_MODULE_ACCESS_LIST"; 
export const GET_MODULE_ACCESS_LIST_SUCCESS = "GET_MODULE_ACCESS_LIST_SUCCESS"; 
export const GET_MODULE_ACCESS_LIST_ERROR = "GET_MODULE_ACCESS_LIST_ERROR";

export const ADD_MODULE_ACCESS_LIST = "ADD_MODULE_ACCESS_LIST"; 
export const ADD_MODULE_ACCESS_LIST_SUCCESS = "ADD_MODULE_ACCESS_LIST_SUCCESS"; 
export const ADD_MODULE_ACCESS_LIST_ERROR = "ADD_MODULE_ACCESS_LIST_ERROR";

export const GET_SEARCH_MODULE_ACCESS_LIST = "GET_SEARCH_MODULE_ACCESS_LIST"; 
export const GET_SEARCH_MODULE_ACCESS_LIST_SUCCESS = "GET_SEARCH_MODULE_ACCESS_LIST_SUCCESS"; 
export const GET_SEARCH_MODULE_ACCESS_LIST_ERROR = "GET_SEARCH_MODULE_ACCESS_LIST_ERROR";