export const GET_COUPON_LIST = "GET_COUPON_LIST"; 
export const GET_COUPON_LIST_SUCCESS = "GET_COUPON_LIST_SUCCESS"; 
export const GET_COUPON_LIST_ERROR = "GET_COUPON_LIST_ERROR";

export const ADD_COUPON_LIST = "ADD_COUPON_LIST"; 
export const ADD_COUPON_LIST_SUCCESS = "ADD_COUPON_LIST_SUCCESS"; 
export const ADD_COUPON_LIST_ERROR = "ADD_COUPON_LIST_ERROR";

export const CHANGE_STATUS_COUPON_LIST = "CHANGE_STATUS_COUPON_LIST"; 
export const CHANGE_STATUS_COUPON_LIST_SUCCESS = "CHANGE_STATUS_COUPON_LIST_SUCCESS"; 
export const CHANGE_STATUS_COUPON_LIST_ERROR = "CHANGE_STATUS_COUPON_LIST_ERROR";

export const DELETE_COUPON_LIST = "DELETE_COUPON_LIST"; 
export const DELETE_COUPON_LIST_SUCCESS = "DELETE_COUPON_LIST_SUCCESS"; 
export const DELETE_COUPON_LIST_ERROR = "DELETE_COUPON_LIST_ERROR";

export const RESET_COUPON_LIST = "RESET_COUPON_LIST"; 
export const RESET_COUPON_LIST_SUCCESS = "RESET_COUPON_LIST_SUCCESS"; 
export const RESET_COUPON_LIST_ERROR = "RESET_COUPON_LIST_ERROR";