export const GET_ROLES_LIST = "GET_ROLES_LIST"; 
export const GET_ROLES_LIST_SUCCESS = "GET_ROLES_LIST_SUCCESS"; 
export const GET_ROLES_LIST_ERROR = "GET_ROLES_LIST_ERROR";

export const GET_SINGLE_ROLES_LIST = "GET_SINGLE_ROLES_LIST"; 
export const GET_SINGLE_ROLES_LIST_SUCCESS = "GET_SINGLE_ROLES_LIST_SUCCESS"; 
export const GET_SINGLE_ROLES_LIST_ERROR = "GET_SINGLE_ROLES_LIST_ERROR";

export const ADD_ROLES_LIST = "ADD_ROLES_LIST"; 
export const ADD_ROLES_LIST_SUCCESS = "ADD_ROLES_LIST_SUCCESS"; 
export const ADD_ROLES_LIST_ERROR = "ADD_ROLES_LIST_ERROR";

export const DELETE_ROLES_LIST = "DELETE_ROLES_LIST"; 
export const DELETE_ROLES_LIST_SUCCESS = "DELETE_ROLES_LIST_SUCCESS"; 
export const DELETE_ROLES_LIST_ERROR = "DELETE_ROLES_LIST_ERROR";

export const GET_RESET_ROLES_LIST = "GET_RESET_ROLES_LIST"; 
export const GET_RESET_ROLES_LIST_SUCCESS = "GET_RESET_ROLES_LIST_SUCCESS"; 
export const GET_RESET_ROLES_LIST_ERROR = "GET_RESET_ROLES_LIST_ERROR";