export const GET_LEAD_LIST = "GET_LEAD_LIST"; 
export const GET_LEAD_LIST_SUCCESS = "GET_LEAD_LIST_SUCCESS"; 
export const GET_LEAD_LIST_ERROR = "GET_LEAD_LIST_ERROR";

export const ADD_LEAD_LIST = "ADD_LEAD_LIST"; 
export const ADD_LEAD_LIST_SUCCESS = "ADD_LEAD_LIST_SUCCESS"; 
export const ADD_LEAD_LIST_ERROR = "ADD_LEAD_LIST_ERROR";

export const MARK_AS_READ_LEAD_LIST = "MARK_AS_READ_LEAD_LIST"; 
export const MARK_AS_READ_LEAD_LIST_SUCCESS = "MARK_AS_READ_LEAD_LIST_SUCCESS"; 
export const MARK_AS_READ_LEAD_LIST_ERROR = "MARK_AS_READ_LEAD_LIST_ERROR";

export const DELETE_LEAD_LIST = "DELETE_LEAD_LIST"; 
export const DELETE_LEAD_LIST_SUCCESS = "DELETE_LEAD_LIST_SUCCESS"; 
export const DELETE_LEAD_LIST_ERROR = "DELETE_LEAD_LIST_ERROR";

export const RESET_LEAD_LIST = "RESET_LEAD_LIST"; 
export const RESET_LEAD_LIST_SUCCESS = "RESET_LEAD_LIST_SUCCESS"; 
export const RESET_LEAD_LIST_ERROR = "RESET_LEAD_LIST_ERROR";