export const GET_ROLES_ACCESS_LIST = "GET_ROLES_ACCESS_LIST"; 
export const GET_ROLES_ACCESS_LIST_SUCCESS = "GET_ROLES_ACCESS_LIST_SUCCESS"; 
export const GET_ROLES_ACCESS_LIST_ERROR = "GET_ROLES_ACCESS_LIST_ERROR";

export const SAVE_ROLES_ACCESS_LIST = "SAVE_ROLES_ACCESS_LIST"; 
export const SAVE_ROLES_ACCESS_LIST_SUCCESS = "SAVE_ROLES_ACCESS_LIST_SUCCESS"; 
export const SAVE_ROLES_ACCESS_LIST_ERROR = "SAVE_ROLES_ACCESS_LIST_ERROR";