export const GET_USER_LIST = "GET_USER_LIST"; 
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS"; 
export const GET_USER_LIST_ERROR = "GET_USER_LIST_ERROR";

export const GET_USER_VIEW = "GET_USER_VIEW"; 
export const GET_USER_VIEW_SUCCESS = "GET_USER_VIEW_SUCCESS"; 
export const GET_USER_VIEW_ERROR = "GET_USER_VIEW_ERROR";

export const ADD_USER_LIST = "ADD_USER_LIST"; 
export const ADD_USER_LIST_SUCCESS = "ADD_USER_LIST_SUCCESS"; 
export const ADD_USER_LIST_ERROR = "ADD_USER_LIST_ERROR";

export const DELETE_USER_LIST = "DELETE_USER_LIST"; 
export const DELETE_USER_LIST_SUCCESS = "DELETE_USER_LIST_SUCCESS"; 
export const DELETE_USER_LIST_ERROR = "DELETE_USER_LIST_ERROR";

export const UPDATE_USER_DATA_LIST = "UPDATE_USER_DATA_LIST"; 
export const UPDATE_USER_DATA_LIST_SUCCESS = "UPDATE_USER_DATA_LIST_SUCCESS"; 
export const UPDATE_USER_DATA_LIST_ERROR = "UPDATE_USER_DATA_LIST_ERROR";

export const RESET_USER_DATA_LIST = "RESET_USER_DATA_LIST"; 
export const RESET_USER_DATA_LIST_SUCCESS = "RESET_USER_DATA_LIST_SUCCESS"; 
export const RESET_USER_DATA_LIST_ERROR = "RESET_USER_DATA_LIST_ERROR";

export const CHECK_USER_LIST = "CHECK_USER_LIST"; 
export const CHECK_USER_LIST_SUCCESS = "CHECK_USER_LIST_SUCCESS"; 
export const CHECK_USER_LIST_ERROR = "CHECK_USER_LIST_ERROR";