export const GET_TAGLOG_LIST = "GET_TAGLOG_LIST"; 
export const GET_TAGLOG_LIST_SUCCESS = "GET_TAGLOG_LIST_SUCCESS"; 
export const GET_TAGLOG_LIST_ERROR = "GET_TAGLOG_LIST_ERROR";

export const ADD_TAGLOG_LIST = "ADD_TAGLOG_LIST"; 
export const ADD_TAGLOG_LIST_SUCCESS = "ADD_TAGLOG_LIST_SUCCESS"; 
export const ADD_TAGLOG_LIST_ERROR = "ADD_TAGLOG_LIST_ERROR";

export const CHANGE_STATUS_TAGLOG_LIST = "CHANGE_STATUS_TAGLOG_LIST"; 
export const CHANGE_STATUS_TAGLOG_LIST_SUCCESS = "CHANGE_STATUS_TAGLOG_LIST_SUCCESS"; 
export const CHANGE_STATUS_TAGLOG_LIST_ERROR = "CHANGE_STATUS_TAGLOG_LIST_ERROR";

export const DELETE_TAGLOG_LIST = "DELETE_TAGLOG_LIST"; 
export const DELETE_TAGLOG_LIST_SUCCESS = "DELETE_TAGLOG_LIST_SUCCESS"; 
export const DELETE_TAGLOG_LIST_ERROR = "DELETE_TAGLOG_LIST_ERROR";

export const GET_SUB_TAGLOG_LIST = "GET_SUB_TAGLOG_LIST"; 
export const GET_SUB_TAGLOG_LIST_SUCCESS = "GET_SUB_TAGLOG_LIST_SUCCESS"; 
export const GET_SUB_TAGLOG_LIST_ERROR = "GET_SUB_TAGLOG_LIST_ERROR";

export const ADD_SUB_TAGLOG_LIST = "ADD_SUB_TAGLOG_LIST"; 
export const ADD_SUB_TAGLOG_LIST_SUCCESS = "ADD_SUB_TAGLOG_LIST_SUCCESS"; 
export const ADD_SUB_TAGLOG_LIST_ERROR = "ADD_SUB_TAGLOG_LIST_ERROR";

export const CHANGE_STATUS_SUB_TAGLOG_LIST = "CHANGE_STATUS_SUB_TAGLOG_LIST"; 
export const CHANGE_STATUS_SUB_TAGLOG_LIST_SUCCESS = "CHANGE_STATUS_SUB_TAGLOG_LIST_SUCCESS"; 
export const CHANGE_STATUS_SUB_TAGLOG_LIST_ERROR = "CHANGE_STATUS_SUB_TAGLOG_LIST_ERROR";

export const DELETE_SUB_TAGLOG_LIST = "DELETE_SUB_TAGLOG_LIST"; 
export const DELETE_SUB_TAGLOG_LIST_SUCCESS = "DELETE_SUB_TAGLOG_LIST_SUCCESS"; 
export const DELETE_SUB_TAGLOG_LIST_ERROR = "DELETE_SUB_TAGLOG_LIST_ERROR";

export const REST_TAGLOG_LIST = "REST_TAGLOG_LIST"; 
export const REST_TAGLOG_LIST_SUCCESS = "REST_TAGLOG_LIST_SUCCESS"; 
export const REST_TAGLOG_LIST_ERROR = "REST_TAGLOG_LIST_ERROR";