export const GET_CROP_LIST = "GET_CROP_LIST"; 
export const GET_CROP_LIST_SUCCESS = "GET_CROP_LIST_SUCCESS"; 
export const GET_CROP_LIST_ERROR = "GET_CROP_LIST_ERROR";

export const ADD_CROP_LIST = "ADD_CROP_LIST"; 
export const ADD_CROP_LIST_SUCCESS = "ADD_CROP_LIST_SUCCESS"; 
export const ADD_CROP_LIST_ERROR = "ADD_CROP_LIST_ERROR";

export const CHANGE_STATUS_CROP_LIST = "CHANGE_STATUS_CROP_LIST"; 
export const CHANGE_STATUS_CROP_LIST_SUCCESS = "CHANGE_STATUS_CROP_LIST_SUCCESS"; 
export const CHANGE_STATUS_CROP_LIST_ERROR = "CHANGE_STATUS_CROP_LIST_ERROR";

export const DELETE_CROP_LIST = "DELETE_CROP_LIST"; 
export const DELETE_CROP_LIST_SUCCESS = "DELETE_CROP_LIST_SUCCESS"; 
export const DELETE_CROP_LIST_ERROR = "DELETE_CROP_LIST_ERROR";

export const RESET_CROP_LIST = "RESET_CROP_LIST"; 
export const RESET_CROP_LIST_SUCCESS = "RESET_CROP_LIST_SUCCESS"; 
export const RESET_CROP_LIST_ERROR = "RESET_CROP_LIST_ERROR";