export const GET_COMPLAIN_LIST = "GET_COMPLAIN_LIST"; 
export const GET_COMPLAIN_LIST_SUCCESS = "GET_COMPLAIN_LIST_SUCCESS"; 
export const GET_COMPLAIN_LIST_ERROR = "GET_COMPLAIN_LIST_ERROR";

export const GET_FARMER_COMPLAIN_LIST = "GET_FARMER_COMPLAIN_LIST"; 
export const GET_FARMER_COMPLAIN_LIST_SUCCESS = "GET_FARMER_COMPLAIN_LIST_SUCCESS"; 
export const GET_FARMER_COMPLAIN_LIST_ERROR = "GET_FARMER_COMPLAIN_LIST_ERROR";

export const GET_COMPLAIN_DETAILS_LIST = "GET_COMPLAIN_DETAILS_LIST"; 
export const GET_COMPLAIN_DETAILS_LIST_SUCCESS = "GET_COMPLAIN_DETAILS_LIST_SUCCESS"; 
export const GET_COMPLAIN_DETAILS_LIST_ERROR = "GET_COMPLAIN_DETAILS_LIST_ERROR";

export const ADD_COMPLAIN_LIST = "ADD_COMPLAIN_LIST"; 
export const ADD_COMPLAIN_LIST_SUCCESS = "ADD_COMPLAIN_LIST_SUCCESS"; 
export const ADD_COMPLAIN_LIST_ERROR = "ADD_COMPLAIN_LIST_ERROR";

export const UPDATE_COMPLAIN_LIST = "UPDATE_COMPLAIN_LIST"; 
export const UPDATE_COMPLAIN_LIST_SUCCESS = "UPDATE_COMPLAIN_LIST_SUCCESS"; 
export const UPDATE_COMPLAIN_LIST_ERROR = "UPDATE_COMPLAIN_LIST_ERROR";

export const DELETE_COMPLAIN_LIST = "DELETE_COMPLAIN_LIST"; 
export const DELETE_COMPLAIN_LIST_SUCCESS = "DELETE_COMPLAIN_LIST_SUCCESS"; 
export const DELETE_COMPLAIN_LIST_ERROR = "DELETE_COMPLAIN_LIST_ERROR";

export const REST_COMPLAIN_LIST = "REST_COMPLAIN_LIST"; 
export const REST_COMPLAIN_LIST_SUCCESS = "REST_COMPLAIN_LIST_SUCCESS"; 
export const REST_COMPLAIN_LIST_ERROR = "REST_COMPLAIN_LIST_ERROR";