export const GET_CUSTOMER_DATA_LIST = "GET_CUSTOMER_DATA_LIST"; 
export const GET_CUSTOMER_DATA_LIST_SUCCESS = "GET_CUSTOMER_DATA_LIST_SUCCESS"; 
export const GET_CUSTOMER_DATA_LIST_ERROR = "GET_CUSTOMER_DATA_LIST_ERROR";

export const ADD_CUSTOMER_DATA_LIST = "ADD_CUSTOMER_DATA_LIST"; 
export const ADD_CUSTOMER_DATA_LIST_SUCCESS = "ADD_CUSTOMER_DATA_LIST_SUCCESS"; 
export const ADD_CUSTOMER_DATA_LIST_ERROR = "ADD_CUSTOMER_DATA_LIST_ERROR";

export const UPDATE_CUSTOMER_DATA_LIST = "UPDATE_CUSTOMER_DATA_LIST"; 
export const UPDATE_CUSTOMER_DATA_LIST_SUCCESS = "UPDATE_CUSTOMER_DATA_LIST_SUCCESS"; 
export const UPDATE_CUSTOMER_DATA_LIST_ERROR = "UPDATE_CUSTOMER_DATA_LIST_ERROR";

export const DELETE_CUSTOMER_DATA_LIST = "DELETE_CUSTOMER_DATA_LIST"; 
export const DELETE_CUSTOMER_DATA_LIST_SUCCESS = "DELETE_CUSTOMER_DATA_LIST_SUCCESS"; 
export const DELETE_CUSTOMER_DATA_LIST_ERROR = "DELETE_CUSTOMER_DATA_LIST_ERROR";

export const BLOCK_CUSTOMER_DATA_LIST = "BLOCK_CUSTOMER_DATA_LIST"; 
export const BLOCK_CUSTOMER_DATA_LIST_SUCCESS = "BLOCK_CUSTOMER_DATA_LIST_SUCCESS"; 
export const BLOCK_CUSTOMER_DATA_LIST_ERROR = "BLOCK_CUSTOMER_DATA_LIST_ERROR";

export const CHECK_CUSTOMER_EXIST_LIST = "CHECK_CUSTOMER_EXIST_LIST"; 
export const CHECK_CUSTOMER_EXIST_LIST_SUCCESS = "CHECK_CUSTOMER_EXIST_LIST_SUCCESS"; 
export const CHECK_CUSTOMER_EXIST_LIST_ERROR = "CHECK_CUSTOMER_EXIST_LIST_ERROR";

export const REST_CUSTOMER_DATA_LIST = "REST_CUSTOMER_DATA_LIST"; 
export const REST_CUSTOMER_DATA_LIST_SUCCESS = "REST_CUSTOMER_DATA_LIST_SUCCESS"; 
export const REST_CUSTOMER_DATA_LIST_ERROR = "REST_CUSTOMER_DATA_LIST_ERROR";