export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST"; 
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS"; 
export const GET_CATEGORY_LIST_ERROR = "GET_CATEGORY_LIST_ERROR";

export const ADD_CATEGORY_LIST = "ADD_CATEGORY_LIST"; 
export const ADD_CATEGORY_LIST_SUCCESS = "ADD_CATEGORY_LIST_SUCCESS"; 
export const ADD_CATEGORY_LIST_ERROR = "ADD_CATEGORY_LIST_ERROR";

export const DELETE_CATEGORY_LIST = "DELETE_CATEGORY_LIST"; 
export const DELETE_CATEGORY_LIST_SUCCESS = "DELETE_CATEGORY_LIST_SUCCESS"; 
export const DELETE_CATEGORY_LIST_ERROR = "DELETE_CATEGORY_LIST_ERROR";