export const GET_PACKING_LIST = "GET_PACKING_LIST"; 
export const GET_PACKING_LIST_SUCCESS = "GET_PACKING_LIST_SUCCESS"; 
export const GET_PACKING_LIST_ERROR = "GET_PACKING_LIST_ERROR";

export const ADD_PACKING_LIST = "ADD_PACKING_LIST"; 
export const ADD_PACKING_LIST_SUCCESS = "ADD_PACKING_LIST_SUCCESS"; 
export const ADD_PACKING_LIST_ERROR = "ADD_PACKING_LIST_ERROR";

export const DELETE_PACKING_LIST = "DELETE_PACKING_LIST"; 
export const DELETE_PACKING_LIST_SUCCESS = "DELETE_PACKING_LIST_SUCCESS"; 
export const DELETE_PACKING_LIST_ERROR = "DELETE_PACKING_LIST_ERROR";