export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST"; 
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS"; 
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR";

export const ADD_PRODUCT_LIST = "ADD_PRODUCT_LIST"; 
export const ADD_PRODUCT_LIST_SUCCESS = "ADD_PRODUCT_LIST_SUCCESS"; 
export const ADD_PRODUCT_LIST_ERROR = "ADD_PRODUCT_LIST_ERROR";

export const DELETE_PRODUCT_LIST = "DELETE_PRODUCT_LIST"; 
export const DELETE_PRODUCT_LIST_SUCCESS = "DELETE_PRODUCT_LIST_SUCCESS"; 
export const DELETE_PRODUCT_LIST_ERROR = "DELETE_PRODUCT_LIST_ERROR";

export const GET_RELATED_PRODUCT_LIST = "GET_RELATED_PRODUCT_LIST"; 
export const GET_RELATED_PRODUCT_LIST_SUCCESS = "GET_RELATED_PRODUCT_LIST_SUCCESS"; 
export const GET_RELATED_PRODUCT_LIST_ERROR = "GET_RELATED_PRODUCT_LIST_ERROR";
