export const GET_MODULE_LIST = "GET_MODULE_LIST"; 
export const GET_MODULE_LIST_SUCCESS = "GET_MODULE_LIST_SUCCESS"; 
export const GET_MODULE_LIST_ERROR = "GET_MODULE_LIST_ERROR";

export const UPDATE_MODULE_LIST = "UPDATE_MODULE_LIST"; 
export const UPDATE_MODULE_LIST_SUCCESS = "UPDATE_MODULE_LIST_SUCCESS"; 
export const UPDATE_MODULE_LIST_ERROR = "UPDATE_MODULE_LIST_ERROR";

export const ADD_MODULE_LIST = "ADD_MODULE_LIST"; 
export const ADD_MODULE_LIST_SUCCESS = "ADD_MODULE_LIST_SUCCESS"; 
export const ADD_MODULE_LIST_ERROR = "ADD_MODULE_LIST_ERROR";

export const DELETE_MODULE_LIST = "DELETE_MODULE_LIST"; 
export const DELETE_MODULE_LIST_SUCCESS = "DELETE_MODULE_LIST_SUCCESS"; 
export const DELETE_MODULE_LIST_ERROR = "DELETE_MODULE_LIST_ERROR";


// Module Group

export const GET_MODULE_GROUP_LIST = "GET_MODULE_GROUP_LIST"; 
export const GET_MODULE_GROUP_LIST_SUCCESS = "GET_MODULE_GROUP_LIST_SUCCESS"; 
export const GET_MODULE_GROUP_LIST_ERROR = "GET_MODULE_GROUP_LIST_ERROR";

export const UPDATE_MODULE_GROUP_LIST = "UPDATE_MODULE_GROUP_LIST"; 
export const UPDATE_MODULE_GROUP_LIST_SUCCESS = "UPDATE_MODULE_GROUP_LIST_SUCCESS"; 
export const UPDATE_MODULE_GROUP_LIST_ERROR = "UPDATE_MODULE_GROUP_LIST_ERROR";

export const ADD_MODULE_GROUP_LIST = "ADD_MODULE_GROUP_LIST"; 
export const ADD_MODULE_GROUP_LIST_SUCCESS = "ADD_MODULE_GROUP_LIST_SUCCESS"; 
export const ADD_MODULE_GROUP_LIST_ERROR = "ADD_MODULE_GROUP_LIST_ERROR";

export const DELETE_MODULE_GROUP_LIST = "DELETE_MODULE_GROUP_LIST"; 
export const DELETE_MODULE_GROUP_LIST_SUCCESS = "DELETE_MODULE_GROUP_LIST_SUCCESS"; 
export const DELETE_MODULE_GROUP_LIST_ERROR = "DELETE_MODULE_GROUP_LIST_ERROR";

// Search Api

export const GET_SEARCH_LIST = "GET_SEARCH_LIST"; 
export const GET_SEARCH_LIST_SUCCESS = "GET_SEARCH_LIST_SUCCESS"; 
export const GET_SEARCH_LIST_ERROR = "GET_SEARCH_LIST_ERROR";

export const GET_SEARCH_GROUP_LIST = "GET_SEARCH_GROUP_LIST"; 
export const GET_SEARCH_GROUP_LIST_SUCCESS = "GET_SEARCH_GROUP_LIST_SUCCESS"; 
export const GET_SEARCH_GROUP_LIST_ERROR = "GET_SEARCH_GROUP_LIST_ERROR";
