export const GET_SALES_DASHBOARD_DATA = "GET_SALES_DASHBOARD_DATA"; 
export const GET_SALES_DASHBOARD_DATA_SUCCESS = "GET_SALES_DASHBOARD_DATA_SUCCESS"; 
export const GET_SALES_DASHBOARD_DATA_ERROR = "GET_SALES_DASHBOARD_DATA_ERROR";

export const GET_CALLBACK_DATA = "GET_CALLBACK_DATA"; 
export const GET_CALLBACK_DATA_SUCCESS = "GET_CALLBACK_DATA_SUCCESS"; 
export const GET_CALLBACK_DATA_ERROR = "GET_CALLBACK_DATA_ERROR";

export const GET_MARK_AS_DONE_DATA = "GET_MARK_AS_DONE_DATA"; 
export const GET_MARK_AS_DONE_DATA_SUCCESS = "GET_MARK_AS_DONE_DATA_SUCCESS"; 
export const GET_MARK_AS_DONE_DATA_ERROR = "GET_MARK_AS_DONE_DATA_ERROR";

export const GET_SALES_DASHBOARD_RESET_DATA = "GET_SALES_DASHBOARD_RESET_DATA"; 
export const GET_SALES_DASHBOARD_RESET_DATA_SUCCESS = "GET_SALES_DASHBOARD_RESET_DATA_SUCCESS"; 
export const GET_SALES_DASHBOARD_RESET_DATA_ERROR = "GET_SALES_DASHBOARD_RESET_DATA_ERROR";