export const GET_BANNER_LIST = "GET_BANNER_LIST"; 
export const GET_BANNER_LIST_SUCCESS = "GET_BANNER_LIST_SUCCESS"; 
export const GET_BANNER_LIST_ERROR = "GET_BANNER_LIST_ERROR";

export const ADD_BANNER_LIST = "ADD_BANNER_LIST"; 
export const ADD_BANNER_LIST_SUCCESS = "ADD_BANNER_LIST_SUCCESS"; 
export const ADD_BANNER_LIST_ERROR = "ADD_BANNER_LIST_ERROR";

export const DELETE_BANNER_LIST = "DELETE_BANNER_LIST"; 
export const DELETE_BANNER_LIST_SUCCESS = "DELETE_BANNER_LIST_SUCCESS"; 
export const DELETE_BANNER_LIST_ERROR = "DELETE_BANNER_LIST_ERROR";

export const REST_BANNER_LIST = "REST_BANNER_LIST"; 
export const REST_BANNER_LIST_SUCCESS = "REST_BANNER_LIST_SUCCESS"; 
export const REST_BANNER_LIST_ERROR = "REST_BANNER_LIST_ERROR";